services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    autoDeploy: true
    envVars:
      - key: TELEGRAM_API_ID
        value: "your_api_id"  # Replace with your real API ID
      - key: TELEGRAM_API_HASH
        value: "your_api_hash"  # Replace with your real API Hash
    plan: free
