services:
  - type: web
    name: telegram-bot-service
    env: python
    plan: starter  # This uses the free plan
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_API_ID
        value: "26371992"  # Optional: You can keep this or remove it if you set it in the dashboard
      - key: TELEGRAM_API_HASH
        value: "c58448dd41aba5eb58a1e72df5c9f9d4"  # Optional: You can keep this or remove it if you set it in the dashboard
      - key: TELEGRAM_PHONE
        value: "+8801866031776"  # Replace with your actual phone number, if you want to set it here
