services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    autoDeploy: true
    envVars:
      - key: TELEGRAM_API_ID
        value: "26371992"  # Replace with your real API ID
      - key: TELEGRAM_API_HASH
        value: "c58448dd41aba5eb58a1e72df5c9f9d4"  # Replace with your real API Hash
    plan: free
