services:
  - name: telegram-bot
    type: web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_API_ID
        value: "26371992"
      - key: TELEGRAM_API_HASH
        value: "c58448dd41aba5eb58a1e72df5c9f9d4"
      - key: TELEGRAM_PHONE
        value: "+8801866031776"
