services:
  - name: telegram-bot
    type: worker  # This is the key part: changing it to a 'worker'
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_API_ID
        value: "your_telegram_api_id_here"
      - key: TELEGRAM_API_HASH
        value: "your_telegram_api_hash_here"
      - key: TELEGRAM_PHONE
        value: "your_phone_number_here"
